#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party/brackets
source $dir/functions/third-party/dropbox
source $dir/functions/third-party/eclipse
source $dir/functions/third-party/google-chrome
source $dir/functions/third-party/oracle-java
source $dir/functions/third-party/spotify
source $dir/functions/third-party/sublime-text
source $dir/functions/third-party/virtualbox
source $dir/functions/third-party/vlc

# Install Third-Party Applications
function thirdparty {
    eval `resize`
    THIRDPARTY=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'brackets'           'Brackets' \
        'dropbox'           'Dropbox' \
        'eclipse'           'Eclipse' \
        'google-chrome'     'Google Chrome' \
        'oracle-java'       'Oracle Java' \
        'spotify'           'Spotify' \
        'sublime-text'      'Sublime Text 3' \
	'virtual-box'               'Virtual Box' \
        'vlc'               'VLC Player' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        $THIRDPARTY
    else
        main
    fi
}
